name = input('请输入你的名字：')
QQ = input('请输入你的qq：')
PhoneNumber = input('请输入你的手机：')
address = input('请输入你的地址：')
print('姓名：{}，年龄为:{}'.format(name,23))
print('QQ：{}'.format(QQ))
print('手机号：{}'.format(PhoneNumber))
print('公司地址：{}'.format(address))
